### ISSUE TITLE
[BUG] Outdated popular list

### ISSUE THREAD

**Issue by oleglucic** [Stremio/stremio-bugs#1007]
**Describe the bug**
In the app, Popular catalogues are often outdated. They get reset only when cache gets removed from the app. This happens only on Android. When on Windows or Web, everything is always up to date.

**To Reproduce**
1. Go to 'Stremio Homepage'
2. Scroll down to 'Popular catalogues section (usually at the top)'
3. See error

**Expected behavior**
Your catalogues will be the same since you last cleared app cache.

**Smartphone:**
 - OS: OneUI 6.1 (Android 14)
 - Version: 1.6.13

**TV:**
 - OS: Android 11 (TV)
 - Version 1.6.12

**Comment by TRtomasz** [comment]
Each addon sets cache headers, there is no bug, and each app will update them once cache expires and is invalid

**Comment by oleglucic** [comment]
Thank you : )

**Comment by jaruba** [comment]
Hi @oleglucic , if this was related to the Cinemeta (official addon) catalogs (Popular / Featured), we looked into this today (specifically because I saw ur report too) and there was an issue on our side regarding the cache headers of the Cinemeta official addon specifically (not community addons)

The Cinemeta addon should refresh much faster from this point forward.

**Comment by oleglucic** [comment]
Thank you so much @jaruba : )
