### ISSUE TITLE
Stremio 4.0.3 - Error during update

### ISSUE THREAD

**Issue by wptd** [Stremio/stremio-bugs#140]
This is the message that Im getting:

> Error while applying shell JS. Please consider re-installing Stremio from https://www.stremio.com
> 
> initShellComm is not defined

**Comment by racuna** [comment]
same here

**Comment by brunojdo** [comment]
same here [2]

**Comment by Ivshti** [comment]
Fixed now

**Comment by mujahidrj** [comment]
How do you fix the error

**Comment by harshit777** [comment]
Got the same error for mac

**Comment by brad457** [comment]
> Got the same error for mac

Got the same error for Windows 7 on latest version, 4.4.116:
![stremioerror](https://user-images.githubusercontent.com/11328764/94487667-5dd3d380-01af-11eb-93b8-4003a801bb2b.png)

**Comment by TRtomasz** [comment]
Hi @brad457 in order to fix this we need your help please do the following:
Before you start turn off stremio
1. Press Win Key + R and type CMD in the window and press enter
![image](https://user-images.githubusercontent.com/40594253/94920972-a2b18000-04b7-11eb-9baf-1e8653eda6c3.png)
2. In cmd windows please type `cd %localappdata%\Programs\LNV\Stremio-4` and press enter 
3. Please type `stremio.exe -remote-debugging-port=9999` and press enter
4. Please open your chrome webbrowser and in the adress bar type `chrome://inspect/#devices`
5. In new webpage please select `discover network targets` and then click configure
![image](https://user-images.githubusercontent.com/40594253/94921307-59156500-04b8-11eb-9815-c09990131802.png)
6. Please type `127.0.0.1:9999` press enter and then click done, that new entry should be added to the list now 
![image](https://user-images.githubusercontent.com/40594253/94921377-83ffb900-04b8-11eb-8b06-f4dea8568528.png)
7. After few seconds you should see Stremio under Remote Target, please click inspect next to it
![image](https://user-images.githubusercontent.com/40594253/94921498-b8737500-04b8-11eb-8e82-0d92853b85a1.png)
8. Now please go to the console tab in new opened window and make screenshot of it, also please make screenshot of network tab please send us this screenshot
![image](https://user-images.githubusercontent.com/40594253/94921638-fc667a00-04b8-11eb-9be6-8888793e19d7.png)
