### ISSUE TITLE
update appimage not works

### ISSUE THREAD

**Issue by Alexis6307** [Stremio/stremio-bugs#162]
Title explain itself. The appimage update functionallity doesn't works.

**Comment by Ivshti** [comment]
i will close this as a duplicate of: https://github.com/Stremio/stremio-bugs/issues/163

even though your issue is older, the other has a stack trace

ther eare other duplicates as well

we're working on a fix of this, but for now it's possible to compile http://github.com/stremio/stremio-shell yourself
