### ISSUE TITLE
Sound desynchronization 

### ISSUE THREAD

**Issue by TRtomasz** [Stremio/stremio-bugs#166]
Recently some users reports problems with the sound desynchronization. In the attachments you can find codec information from their system.

**Environment**
Windows 10
Stremio 4.4.10

**Codec Informations**
If you have similiar problem and you would like to help us and send your codec information here are two ways to get the info:
1. On the Help menu in Windows Media Player, select About Windows Media Player. 
If you can't see the Help menu, select Organize, select Layout, and then select Show menu bar.

2. In the About Windows Media Player dialog box, select Technical Support Information.
Your web browser will open a page that includes a lot of detailed info about the related binary files, codecs, filters, plug-ins, and services installed on your PC. 

Second way: You can install Nirsoft InstalledCodec and use it to get codec information

**Temporary Fix**
Simply going back 15 sec( left arrow) or pausing and resuming play is (temporary) fixing issue.

 

**Attachments**
[Support Information for Windows Media Player.pdf](https://github.com/Stremio/stremio-bugs/files/2552901/Support.Information.for.Windows.Media.Player.pdf)
[Windows Media Player codec etc.pdf](https://github.com/Stremio/stremio-bugs/files/2552902/Windows.Media.Player.codec.etc.pdf)

**Comment by sispus** [comment]
I had this problem in manjaro linux.

**Comment by TRtomasz** [comment]
@sispus  Can you try turn off hardware decoding in the settings and then check if it still happens?

**Comment by sispus** [comment]
Disabling hardware acceleration didn't fix it.

**Comment by TRtomasz** [comment]
and does it happen for every video? Like youtube videos also?

**Comment by sispus** [comment]
I tried vimeo, it seems normal for 10 min trial. 
I also installed youtube addon for trying, but I couldn't play any youtube video now. I don't know why.

There isn't any chance that #174 is related, is there? I don't know nothing about shell or something, but I have suspected, because this problem is new for me with 4.4.25 .xz install. 
4.4.10 appimage version was normal.

**Comment by Ivshti** [comment]
I think there's a chance it might be related. This error means that the shell will not be using the usual MPV player but will be fallbacking to HTML5.

What kind of addons are you using? Are you sure there's no other problems (such as incompatible streams) on your system?

**Comment by sispus** [comment]
I'm using juan carlos 2, popcorn time, rar, iberian, piratebay, zooqle, anime addon, estream and all the official ones. (I don't know how to choose doubled addons, just choose ones with bigger version number).
My browsers and vlc work without problem, i assume. 
I think not all the videos cause this sync. problem, but it is not addon based - i mean, while watching from the same addon an episode of a serial may have problem but other don't. but, for example the movie "yes man" did it for playing from several sources whenever I tried to play, wherever I start the video, in a couple of minutes later. I don't know how to collect more info on this issue. 

also, i don't have "play with vlc" or similar thing in settings, I think there were such an option. beside, I have an option for "launch player in separate window" but I couldn't figure out what it means since selecting it changes nothing for me.

**Comment by TomerBrosh** [comment]
Also got this problem. the "fix" to pause and replay clearly shows a few frames skipping forward, so maybe the frame rate is faster than what its supposed to be?

**Comment by TRtomasz** [comment]
I'm closing this issue for now. If you still have this problem on latest 4.4.116 Stremio version please let us know.
