### ISSUE TITLE
OpenSubtitles not working with http streams

### ISSUE THREAD

**Issue by TheBeastLT** [Stremio/stremio-bugs#178]
When opening a stream with http stream or hls stream, there are no subtitles loaded for these streams and the Opensubtitles addon shows an error `empty result returned from SearchSubtitles`. Are subtitles only available for torrent type streams?

**Comment by TheBeastLT** [comment]
Seems to be working correctly now. Maybe it was some fluke.. Closing,

**Comment by Ivshti** [comment]
@TheBeastLT I can think of a few reasons why this might happen

* stremio has not identified the playing item with an IMDB ID
* the opensubtitles add-on is buggy and provides the wrong error message/does not form the query well

Otherwise, theoretically stremio should compute an opensubtitles hash for everything (http, torrent, local file) and find the relevant subtitles on opensubtitles via the opensubtitles add-on

let us know if this reappears
