### ISSUE TITLE
Streamio on android TV stuck on load screen

### ISSUE THREAD

**Issue by tnt22** [Stremio/stremio-bugs#209]
Hi,
Im having issues using v1.2.0
Trying to start the app its getting stuck on load screen(with the purple triangle) , if i cleared the catch i can get as far as the login screen and then selecting the guest login it takes like 5 min but then it passes to main screen and always loading with the spinning circle.
It used to work a few days ago. 
Tried to reinstall, didnt work. 
Please help, im board...

**Comment by DECAPRI0** [comment]
Same, this is not a fix. 
I think its because of type of Wi-Fi or router settings. I'm using a mobile hotspot device(netgear mr1100) as my 
Wi-Fi and I changed it's settings before.
If I switch to my phone's mobile data, app goes through with no problem,  movie loads but not fast at my location, so then I switch to Wi-Fi, app loads movie and does it faster. Stremio is able to detect if you are using Wi-Fi or Mobile Data.

**Comment by imurreflection** [comment]
Did you try 0.45.1 or 0.45.0 from Aptoide TV. This version is optimized for Android TV
