### ISSUE TITLE
DLNA stream name is wrong

### ISSUE THREAD

**Issue by bsphere** [Stremio/stremio-bugs#33]
I'm playing from Stremio to a OpenELEC/Kodi box through DLNA and the stream name is wrong,
it says "Stremio Video" instead of the actual stream name. this prevent handling of subtitles from Kodi in a usable way..

**Comment by Ivshti** [comment]
what should it be so that subtitles work?

**Comment by bsphere** [comment]
I think that for the best it should be the torrent title (release name), so a player like Kodi can search in opensubtitles..

**Comment by Ivshti** [comment]
There are a few problems with this

1. stremio doesn't receive torrent name from the add-on, as it only returns infoHash and optionally stream name, which is normally file name
2. it's possible to get it from the streaming engine, but it's a separate component which barely communicates with the app - the player is just set to stream from URL/infoHash/fileIndex
3. **Third, and most importantly, I've noticed characters like . and - confuse some TVs and that's why the video title is elementary**

On the other hand, Stremio passes the proper srt file in the DLNA message using 2 separate methods which work with different types of TVs and DLNA receiver apps. So I'd rule that a Kodi issue
