### ISSUE TITLE
Small nitpick stuff

### ISSUE THREAD

**Issue by PoPzQ** [Stremio/stremio-bugs#334]
Hey, the laziest living being on the planet here.
Something that really kinda annoys me is every time a new automatic episode or the 'Next in series' plays I gotta get up from the couch and move my cursor for it to automatically disappear. 
Also, I can't seem to index both Comedy and top IMDB in Stremio version 4.4.142, the closest thing when sorting under IMDB is black comedy lol which I have nothing against
I love Stremio and free shit, all you are amazing!!

**Comment by TRtomasz** [comment]
Please next time check the settings, because this stuff is configurable 
![image](https://user-images.githubusercontent.com/40594253/145012329-d9531750-5d72-42a4-9650-3ffe6ae504a0.png)
Not sure what other addon you were checking, but i'v just checked and Comedy is listed as genre
![image](https://user-images.githubusercontent.com/40594253/145012484-bde50296-7e16-4ca3-ac90-21a465c1836f.png)
