### ISSUE TITLE
Any way to manually 'throttle' streaming speed?

### ISSUE THREAD

**Issue by Darkmaster006** [Stremio/stremio-bugs#340]
I would like to know if there's any way to manually stop the streaming speed at a certain threshold. Let's say my internet has 2 MB/s max, can I have Stremio only use 500 kb/s, or 1 MB/s? This would be very useful, as sometimes my internet/modem seems to stop working or disconnect itself when it's being used too much. This way, that would not happen. Thank you.

**Comment by TRtomasz** [comment]
Hi, you can go to Settings -> Streaming -> torrent profile -> set it to slow

**Comment by Darkmaster006** [comment]
> Hi, you can go to Settings -> Streaming -> torrent profile -> set it to slow

Hello, thanks for the help. I assume you mean 'soft'? This is the Windows version:
![imagen](https://user-images.githubusercontent.com/21136515/147284899-3e1fdab3-509e-4a02-8de0-1c479195fe6b.png)
From what I've tried, it seems to throttle it to 95% of capacity. But is there no way to manually set the speed? This would be a cool thing to implement, if possible, so I leave it as a suggestion. Sorry for the bother, and thank you very much.

**Comment by TRtomasz** [comment]
Yes it is possible @Darkmaster006  here is the instruction https://blog.stremio.com/modify-bittorrent-settings/

**Comment by Darkmaster006** [comment]
> Yes it is possible @Darkmaster006 here is the instruction https://blog.stremio.com/modify-bittorrent-settings/

Thank you.

**Comment by salahmed-ctrlz** [comment]
Yes, you can definitely do that. Your modem is likely disconnecting because it's being overloaded with too many simultaneous connections from the torrent, which is a common issue.

You can fix this by creating a `server-settings.json` file to manually limit Stremio's connection count and download speed.

-----

### **How to Create the Configuration File**

First, make sure Stremio is completely closed.

The location of the settings folder depends on your operating system:

  - **Windows:** `%appdata%\stremio\stremio-server`
  - **macOS:** `~/Library/Application Support/stremio-server`
  - **Linux:** `~/.stremio-server`



1.  Navigate to the correct folder for your OS. If the `stremio-server` folder doesn't exist, create it.
2.  Inside that folder, create a new file and name it exactly `server-settings.json`.
3.  Open the file with any text editor.

-----

### **Set Your Speed and Connection Limits**

Copy and paste the following code into your `server-settings.json` file. This example will limit your speed to **1 MB/s**.
**(Or copy paste your file content to a good AI agent I recommend Gemini 2.5 Pro and have it rewrite the file for you)**

```json
{
  "btMaxConnections": 50,
  "btDownloadSpeedHardLimit": 1048576
}
```

  - `"btMaxConnections": 50`
      - This is the most important setting. It limits the number of connections to prevent your modem from being overloaded. 50 is a very safe number.
  - `"btDownloadSpeedHardLimit": 1048576`
      - This sets the maximum download speed in **bytes per second**. The value `1048576` is exactly 1 MB/s.

If you want to set it to **500 kb/s**, you would change that line to:
`"btDownloadSpeedHardLimit": 512000`

Save the file, and the next time you launch Stremio, it will use these new limits. This should prevent your modem from disconnecting.
