### ISSUE TITLE
Javascript issue (Windows 10)

### ISSUE THREAD

**Issue by Rayoen** [Stremio/stremio-bugs#37]
I recently updated Stremio(Windows 10), when i try to open it, it result with this error...

![capture d ecran 13](https://cloud.githubusercontent.com/assets/17140374/12914216/5e17ea5c-cf23-11e5-91fb-5aea8638e5a1.png)

I Don't know what to do, so i might need a little help here.
And sorry for my bad English!
Thank you

**Comment by Ivshti** [comment]
Did you try dooing a clean install from the website? -> http://www.strem.io

**Comment by Rayoen** [comment]
Yes, but it didn't work, same error...
Thank youfor the fast answer!

**Comment by Rayoen** [comment]
![capture d ecran 14](https://cloud.githubusercontent.com/assets/17140374/12914654/fd18596e-cf25-11e5-993a-de3932a86677.png)

**Comment by Rayoen** [comment]
Little update: Avast! may have blocked stremio...
Anyway , I disabled Avast! and Stremio works now!
Also: thank you for making stremio! I used to use Popcorn Time, but when iI discovered stremio...
It's very beautiful and easy to use and the quality of the films are very impressive.
But if you can increase the ammount of streams, it will be wonderful!

Thank you for your concern of my problem.

**Comment by Ivshti** [comment]
@Rayoen glad to help! ALso, now we know what's the issue.

Re streams: we don't develop any torrent-related add-ons. We don't want to, for a number of reasons. It also ensures the sustainability of our product. 

Those sources are shown because they're popular in your area, but we'll specifically stop showing them to avoid confusion. 

Users would still be able to enable any source through the add-on catalogue: http://addons.strem.io

**Comment by Rayoen** [comment]
RE issue: can you please fix it asap( for other W10 users)?

**Comment by Ivshti** [comment]
@Rayoen can you please try http://www.strem.io/Stremio3.5.6.exe 

We need testing of this version, as it's supposed to fix most of the issues with 3.5.5
