### ISSUE TITLE
[Android TV] Subtitle delay not reseting after changing context

### ISSUE THREAD

**Issue by kanytu** [Stremio/stremio-bugs#457]
**Describe the bug**
Subtitle offset seems to be an app configuration and it is not reseting when changing subtitles or changing movie

**To Reproduce**
1. Play a movie with subtitles
2. Set an delay (in seconds)
3. Leave current playback
4. Start another playback of a different movie
5. Select subtitles

**Expected behavior**
Subtitle delay should be 0s

**Actual behavior**
Subtitle delay is the same as previously defined.

**Android TV  (please complete the following information):**
 - Device: sony xr-55a80j
 - OS: Google TV

**Additional context**
It doesn't make much sense to save the delay as an user setting since this is a configuration for the current playback and current subtitles. Changing subtitles or changing the current stream should reset the delay back to 0

**Comment by jaruba** [comment]
@kanytu Hi, can you justify the reasoning behind this? I believe that subtitle offset is an overall app setting across all our apps (for all platforms) not just Android TV.

One would presume that if you want a subtitle to be towards the top of the screen, you would want it to always be towards the top, not just for the current video you are watching.

The reason that the setting is available within the playback settings is because you cannot reposition subtitles on the screen if they are not visible during the process of repositioning. (as is the case from the main app settings)

**Comment by kanytu** [comment]
Hey @jaruba 

I believe the offset in question is the offset in seconds of the subtitle. Maybe I was not clear on my original description. Let's call it "delay" for simplicity.

My current use case is that some subtitles are not syncronized so I have to manually set a delay for them (in seconds). When I change the subtitle or the stream, it should be assumed that a new subtitle is correctly synced and the delay should be reset back to 0s

I hope the issue is clearer

Thanks.

**Comment by jaruba** [comment]
@kanytu if that is the case, it may indeed be a bug, we will investigate, thank you for reporting it

**Comment by jaruba** [comment]
@kanytu does this happen only when binge watching? (going from one episode to the next) or also when changing the movie / series with a different one?

**Comment by kanytu** [comment]
So I went to record a video of the behaviour and indeed the delay is reseting for 0s when changing stream, even when bing watching. At least now, I don't know if that could behave differently for other streams.

However, what is still confirmed is switching subtitles and the delay not reseting.

**Comment by TRtomasz** [comment]
this should be fixed already
