### ISSUE TITLE
Stop buffering when movie is paused in Xiaomi tv box

### ISSUE THREAD

**Issue by sosajuanaugusto** [Stremio/stremio-bugs#474]
When i play a movie and pause it to buffer the entire file, the download speed go down to 0 in a few megabytes are downloaded
**To Reproduce**
1. Go to some movie and play it
2. Click pause
3. Go to the speed downloading information

**Expected behavior**
The movie has to download entire

 - Version 1.5.11

 - Device: Xiaomi tv box

**Comment by TRtomasz** [comment]
This is not a bug. Looks like you reported same issue on zendesk reddit and here. Really there is no need to do this.
So i will answer once again - When using torrent streams we download only amount that fits in memory buffer because there is no cache on android tv because android tv devices does not have storage.

**Comment by jaruba** [comment]
we removed the disk storage option for android tv because it was the primary cause of crashes (when android tv devices run out of disk space)

currently only in-memory cache is allowed on android tv for this reason, and in-memory cache can only buffer a small amount in RAM

so this is not a bug, and it is not an error, it is the expected behavior, because android tv devices normally have very little disk space available

**Comment by sosajuanaugusto** [comment]
Thank you for the response. My tv box has 8Gb storage and i added 2TB pen
drive. Can i install the android version or another to continue downloading
with that storage?

**Comment by TRtomasz** [comment]
You can download android version from our webpage but you will have to disable auto updates otherwise it will automatically update to the TV app. Also i beleive it was never tested if cache works fine with such setup so we cannot gurantee this.

**Comment by sosajuanaugusto** [comment]
Ok, thanks for the clarification.
