### ISSUE TITLE
3.5.10 Subtitles does not appear on MacOS

### ISSUE THREAD

**Issue by janolara** [Stremio/stremio-bugs#51]
Hi all
Today Stremio has automatically updated to 3.5.10 but when I play something subtitles option does not appear on the app player.

**Comment by Ivshti** [comment]
You'll have to help with more information, because I use Mac OS X as well and subtitles are OK on 3.5.10

I think this is an issue that has nothing to do with version or OS, but appears randomly sometimes.

I've heard reports of it, on different OS's and different updates.

Please do this:
```
/Applications/Stremio.app/Contents/MacOS/Electron . --development
```

Play something, and report the results with screenshots of the dev console.

**Comment by janolara** [comment]
lvshti, it looks like it was a reboot issue, I ran the app with the suggested command and it fixed it.

Thanks
