### ISSUE TITLE
STREMIO Fmovies addon NOT LOADING

### ISSUE THREAD

**Issue by MEDIVH1992** [Stremio/stremio-bugs#571]
The addon Fmovies on stremio is not loading so i can´t watch anything anymore with it.......you can see it loading but when the loading is done it wont pop up in the list to start watching with fmovies 1080/720/........ ...pls fix Fmovies addon

**Comment by jaruba** [comment]
that's a community built addon, it was not built by us, we only handle app issues, not addon issues

**Comment by MEDIVH1992** [comment]
Thats the only awnsers that i see that you are giving to all others wirh issues ....wtf do you guys actually do then .lol

**Comment by jaruba** [comment]
Imagine that u were an architect and designed a very beautiful building that can house 500 people. You build this building and the area becomes a tourist spot, where many tourists come to visit every day just to see the building / take pictures of it. Because the area is now popular, a wine shop opens downstairs (within this building). A tourist comes one day, drinks wine at the wine shop, does not enjoy it and calls the architect:
- I didn't like the wine at the wine shop in your building, can you fix it?
- I'm sorry, but I have no relation whatsoever to the wine shop
- wtf do you guys actually do then .lol

**Comment by kraemi** [comment]
Perfect answer from @jaruba. The issue is now ready to be closed.

**Comment by blackjesusdavid** [comment]
stremio nada mal videos audio español,perú.
