### ISSUE TITLE
Samsung TV Bugs

### ISSUE THREAD

**Issue by davidbaguetta1** [Stremio/stremio-bugs#624]
This is a list of bugs I've encountered so far on the new Samsung TV Stremio app:

Stremio version: Theater v1.0.0
Samsung TV Model: Q70C

Subtitles:
- **Embedded subtitles are not being loaded** - When I was watching an anime, I noticed multiple English subtitles on my tv. I tried every single one, but they were all out of sync. Then I tried the same anime on my phone and noticed the subtitles it loaded worked perfectly. Turns out the phone automatically loaded the embedded subtitles, which were perfectly synced. But I couldn’t find those same subtitles anywhere on the tv.
- **No option to manually sync subtitles** - In the computer, I can easily add or remove delay from subtitles to try to sync them. However, that is not possible on the tv.

Overlay:
- **Stremio overlay sometimes doesn’t disappear automatically, it stays on screen** - I have to quit what I am watching and open it again for it to start behaving normally again. Don't know how to reproduce, haven't found any pattern yet.
- **My cursor randomly disappears in the overlay** - I press, for example, UP on my remote, it shows the overlay with the cursor hovering on the play/pause button. If I press UP again, the cursor randomly disappears from the overlay and I can’t get it to show up again, no matter how many times I press DOWN or any other button. The only way to fix it is to wait a few seconds for the overlay to automatically disappear and then pressing a button again and the overlay and cursor show up again.

Others:
- **My Samsung TV remote has a dedicated play/pause button which does not work on Stremio.**

**Comment by gustavopergola** [comment]
Except for "Embedded subtitles are not being loaded", I can confirm it also happens on model UN55TU8000GXZD

**Comment by chestermw** [comment]
I can add more to the Overlay issues:

**Stremio overlay sometimes doesn’t disappear automatically, it stays on screen**:
I have noticed that the overlay does not disappear when you change the subtitles while the video is playing. For some reason, when you select a new subtitle source, the player controls turn into pause, whilst the actual video is still playing. This makes Stremio think that the video was paused; hence, keeping the overlay on top.

**My cursor randomly disappears in the overlay**:
Not really random, but happens when you overclick on the buttons. e.g.
* On the main menu or anywhere. if you click to the left and kept on clicking left, then you lose the cursor. The only way to fix this is to fully close the app and open again.
* Overlay: same thing. 
This is a constant behaviour observed when the cursor is already on the topmost/leftmost/rightmost/bottom of any available menu/button on the screen and the user accidentally/intentionally clicks further on the same direction.

**Comment by RaptaG** [comment]
I believe the lack of the manual sync option is an important one, since it makes many movies unwatchable for people who don't know English

**Comment by shadyabdou** [comment]
The play/pause button works fine by me on Samsung TV Q70
