### ISSUE TITLE
Volume stuck at 50% when adjusting with scroll wheel

### ISSUE THREAD

**Issue by opposesow** [Stremio/stremio-bugs#660]
**Describe the bug**
When adjusting the volume using the scroll wheel it only goes up to 50%. Even if I set the volume to be higher manually (with the mouse cursor or with the arrow keys on my keyboard), once I touch the scroll wheel it comes back to 50%. I can set it lower with the wheel but not louder than 50%.

**To Reproduce**
1. Open a video
2. Try to adjust volume with scroll wheel

**Expected behavior**
Being able to set the volume from 0% to 100% using the scroll wheel.

**Screenshots**

![image](https://github.com/Stremio/stremio-bugs/assets/80776140/f2f9c92d-3b9a-4d4c-b2fb-11e1fea989cb)

**Desktop (please complete the following information):**
 - OS: Windows 11 22H2 22621.2428
 - Stremio version: 4.4.165

**Comment by TRtomasz** [comment]
this is intended and not a bug, this is not 50% it is 100% what is higher is artificial audio boost.

**Comment by opposesow** [comment]
that's a weird design choice, why only with the scroll wheel? if i use the arrow keys there's no such problem
also if it's intended there should be a visual clue about it or maybe some kind of warning? maybe a text showing 0% 100% and 200%?
and finally i don't understand why it changed, it used to work perfectly in version 3
from a user experience perspective it is a bug.

**Comment by jaruba** [comment]
the only time scroll went to full volume was before we added support for 200% volume, going over 100% volume can damage ur speaker (and maybe ur ears too if ur not careful and have a surround sound system), so scrolling to it is dangerous

the only reasonable time to ever go over 100% volume is when u are trying to watch videos that have surround sound (5.1 or 7.1 audio) on a stereo system, which will use only 2 channels from the full spectrum resulting in much lower volume

this imo is caused by user error, users should only try to play videos that are supported by their system

i agree that the UX could be improved by showing the volume percent on the screen too, but this is not a priority task

**Comment by opposesow** [comment]
there's nothing indicating that this is a 0 to 200% fader or that previously it only went to 100%. if it's dangerous there should be a warning or at least some kind of indication (like VLC does).

as a user i see a fader with no labels i assume it goes from 0 to 100% like any other app/streaming service. i had no idea (and no way to tell) that going over the middle of the fader it's actually boosting the volume
