### ISSUE TITLE
Importing subscriptions

### ISSUE THREAD

**Issue by Harith163** [Stremio/stremio-bugs#69]
quick question(s)
1) Can I somehow quickly import my youtube subscriptions? I have over 250 of them and it is a pain to add them one by one.
2) Can the youtube channel's video notifications be instant? I have noticed that they take a bit of time to show.

**Comment by Ivshti** [comment]
Hello, actually - we're glad we're receiving this request - the only reason we haven't implemented importing of subscriptions is because we thought nobody would ask for it.

We'll add it to our pipeline.

2 is technically difficult, because we have to call the youtube api (which has limits), but we strive to do 5-10 minutes at best; sometimes it takes a bit more

**Comment by Ivshti** [comment]
I personally follow ~30 channels in stremio and I get overflowed by notifications. Interesting how that would feel with 250 :)
