### ISSUE TITLE
Picture Alignment Issue in Full Screen Mode at 600x800 on macOS Ventura

### ISSUE THREAD

**Issue by theserdzo** [Stremio/stremio-bugs#744]
When in full-screen mode at a resolution of 600x800 on macOS Ventura, the stream picture fails to center properly. It does not consider horizontal alignment or the width of the video. 
As a workaround, I currently use VLC player where the video scales properly. 

Limited knowledge of video parameters like scaling with or without black bars complicates troubleshooting efforts.

Steps to Reproduce:
1. Set the resolution to 600x800 running macOS Ventura.
2. Open the Streamio.
3. Begin streaming a video.
4. Enter full-screen mode.

Expected Behavior:
The stream picture should be centered properly within the screen at the specified resolution.

Actual Behavior:
The stream picture is not centered properly in full-screen mode, not considering horizontal alignment or width of video format.

Workaround:
Use Play in VLC player option where the video scales properly.

Environment:
- Operating System: macOS Ventura
- Device: [Macbook Pro 2018 intel gen]
- Application Version: [Latest Version]

Priority: High
Severity: Moderate

Attachments:
[Optional: Screenshots or video recordings demonstrating the issue]

Note:
Further investigation is required to pinpoint the root cause of the alignment issue, especially at the specified resolution on macOS Ventura, and to implement an effective resolution.

**Comment by TRtomasz** [comment]
Sorry we do not plan to support such resolutions lik 600x800

**Comment by jokubasver** [comment]
I'm experiencing the same issue, just on Windows, and 768x576 and below.

Why such a low resolution in modern times? I have a CRT TV connected to my PC using an AMD graphics card, CRT Emudriver, VGA to RGB SCART cable. That's as high of a resolution as this setup can display.

Sure this is an edge case, but I can't imagine that this is a difficult problem to solve.

Otherwise via VLC, video content looks beautiful on a CRT TV via RGB :)
