### ISSUE TITLE
Can't adjust subtitles while input isn't English

### ISSUE THREAD

**Issue by shakedbr** [Stremio/stremio-bugs#77]
If the current input language in Windows isn't english, it's not possible to use the 'G' and 'H' keys to adjust the subtitles .

Thanks!

**Comment by Ivshti** [comment]
great catch, thanks! Any proposals for a way to implement a fix in JS?

**Comment by shakedbr** [comment]
I'm not so familiar with JS, but I think you should use  keyCode instead of charCode as a keyboard event.
so G is "71" and H is "72".

**Comment by Ivshti** [comment]
This is now fixed in our development branch. Unfortunately our release cycle is a bit paused at the moment, as we did full refactor on the desktop app in order to make code sharable with the the upcoming mobile apps. We also improved many other things - hopefully in 1-2 months we'll have a downloadable alpha of our 4.0 release.

**Comment by shakedbr** [comment]
Awesome!
