### ISSUE TITLE
Audio not in sync with video on my 4th gen Apple TV

### ISSUE THREAD

**Issue by tychop** [Stremio/stremio-bugs#78]
When I play a movie, the audio is out of sync on my 4th gen Apple TV. When I play the movie on my laptop, the sound is fine. Tested on two different Apple TV's.

It starts out fine, but as time passes by, the delay gets bigger... 
After 5 minutes, the movie is unwatchable....

**Comment by Ivshti** [comment]
Yes, we are working to resolve this. it's a problem in our HLS converter, it will be resolved with the next major iteration, scheduled for December

in the meantime, we suggest you try playing with VLC, copying the link to quicktime, and then casting to appletv.

casting from quicktime directly (via "play in quicktime") may not work, because it would still get converted to HLS

**Comment by hegelstad** [comment]
Still have this problem :(

**Comment by Ivshti** [comment]
Airplay has been discontinued a long time ago, closing
