### ISSUE TITLE
No playback bar on mainly TV series. Debug code included

### ISSUE THREAD

**Issue by jdraper12** [Stremio/stremio-bugs#85]
I am using stremio-3.6.5 on Ubuntu 14.04. Watching movies and TV series, for the most part, is fine. 

An issue I've been having whilst watching TV series ever since the early releases, however, is that the playback bar showing the time and playback position is completely purpled out, as seen here: 

![screenshot from 2016-11-22 23 42 33](https://cloud.githubusercontent.com/assets/23667917/20546500/617393dc-b10d-11e6-8fd9-db52762c2153.png)

Furthermore, using either the left or right arrow keys will result in the video jumping forward as thought the right arrow key was pressed.

Debug code is as follows:

`user@mycomputer~$ ./Apps/Stremio/Stremio.sh`
`ASAR path detected: /home/user/Apps/Stremio/resources/app.asar, app dir: /home/user/Apps/Stremio`
`ffmpeg located -> undefined`
`EngineFS server started at http://192.168.0.35:11470`
`setting window mode to: main with aspect: undefined`
`-> /381ae7c4ba8f1c8597239cf3e32a1691da58b368/122 bytes=0-`
`-> /381ae7c4ba8f1c8597239cf3e32a1691da58b368/122 `
`-> /381ae7c4ba8f1c8597239cf3e32a1691da58b368/122 bytes=8570-`
`[0x710fd6c3458] avi demux error: no key frame set for track 0`
`[0x710fd6c3458] avi demux error: no key frame set for track 1`
`[0x710fd6c3458] avi demux error: no key frame set for track 0`
`[0x710fd6c3458] avi demux error: no key frame set for track 1`
`[mpeg4 @ 0x710fd866c00] Invalid and inefficient vfw-avi packed B frames detected`
`-> /381ae7c4ba8f1c8597239cf3e32a1691da58b368/122 bytes=0-65535`
`Fontconfig warning: FcPattern object size does not accept value "0"`
`-> /381ae7c4ba8f1c8597239cf3e32a1691da58b368/122 bytes=183382016-183447551`
`Fontconfig warning: FcPattern object size does not accept value "0"`
`Fontconfig warning: FcPattern object size does not accept value "0"`
`Fontconfig warning: FcPattern object size does not accept value "0"`
`[0x710fd917a98] main vout display error: Failed to change zoom`
`[0x710fd917a98] main vout display error: Failed to set on top`
`[0x710fd917a98] main vout display error: Failed to change source AR`
`[0x710fd6c3458] avi demux error: shouldn't yet be executed`
`[mpeg4 @ 0x710fd866c00] warning: first frame is no keyframe`
`setting window mode to: player with aspect: 1.3333333333333333`
`[0x710fd6c3458] avi demux error: shouldn't yet be executed`
`[mpeg4 @ 0x710fd866c00] warning: first frame is no keyframe`

Cheers in advance!

**Comment by Ivshti** [comment]
This is a very nasty and known issue

VLC does not attempt to retrieve the duration/seeking headers of AVI files if they're over HTTP

To fix that for Windows/Mac, we compile custom VLC, but for Linux it's better to use the distro packages for a lot of reasons and plus we don't have the resource to maintain custom builds

The patch is here: https://github.com/Ivshti/vlc-2.2/commit/b65ed7b2d4c82c74d387a819c7e2d8e7b0f58548

If you're braver, you can try: 
1) run with our bundled distribution of VLC, by running `Stremio.sh` instead of `Stremio-runtime`
2) copy libavidemux from our distribution to your system's
3) compile VLC from our source: https://github.com/Ivshti/vlc-2.2
