### ISSUE TITLE
Android TV icon is not rendered correctly

### ISSUE THREAD

**Issue by zukove** [Stremio/stremio-bugs#858]
Android TV icon/tile looks strange with white bezels in it's corners.
Nvidia Shield
Android TV 9.1.1
Stremio 1.6.11
![448235113_8492581447436692_8680995745836275708_n](https://github.com/Stremio/stremio-bugs/assets/22352496/6ac57f39-0882-47d2-9857-d9f6ae449de5)

Screenshot uploaded.

**Comment by TRtomasz** [comment]
This is not a stremio issue but Android TV issue where they do not render banners correctly.

**Comment by The-Choo-Choo-Shoe** [comment]
> This is not a stremio issue but Android TV issue where they do not render banners correctly.

Are you sure? From what I can tell the Stremio banner has transparent rounded corners in the banner itself which causes it to render like this, if you swap launcher you won't even have grey corners all you get is transparent so that's the design of the banner, no?

From what I can tell the icon and banner is supposed to be square: https://developer.android.com/design/ui/tv/guides/system/tv-app-icon-guidelines

Stremio is the only banner that looks like this, I don't think it's an Android TV render issue.

**Comment by TRtomasz** [comment]
we use adaptive icon/banner @The-Choo-Choo-Shoe  bug is android os bug https://issuetracker.google.com/issues/241478271
