### ISSUE TITLE
Meta endpoint for custom stremio addon not working on android clients

### ISSUE THREAD

**Issue by odd-willingness** [Stremio/stremio-bugs#893]
I am working on a custom addon hosted as a flask server on vercel. The addon manages its own media items with custom ids and not the imdb/tmdb ids. As such, the metadata is served at the `/meta/<type>/<id>.json` endpoint.
All endpoints of the addon (/catalog, /meta, /stream) work perfectly fine on the windows, linux and mac stremio clients.
The /catalog endpoint works fine on the android client. When clicking on a catalog entry though, the following error pops up: `Error retrieving information about this`. The /meta endpoint is successfully called, as seen from the backend and a 200 response is returned.

There is an old [comment](https://github.com/Stremio/stremio-addon-sdk/issues/130#issuecomment-653554667) from 2020 by jaruba:
Stremio Android
does not currently support meta links at all
This is all I found when looking for differences in the behaviour between the desktop and android clients.

Note: [stremio-consumet-addon](https://github.com/sleeyax/stremio-consumet-addon) also seems to be providing metadata for custom items and works on android too.

**Comment by jaruba** [comment]
there is a lot of confusion in ur comment, let's try to make some sense of it:
- meta links is not the same as the metadata page, meta links are when u provide a stream that links back to the app on a different page
- meta pages (from "meta" resource in addons) works on all platforms
- "android" is too general, where doesn't it work? is it the android tv app or the android mobile app?

**Comment by jaruba** [comment]
to further explain some things:
- the following projects use stremio-core: android tv, stremio web, samsung tv, lg tv
- the following project use an old version of the core (prior to the rewrite): desktop app, android mobile (these will also be ported to the new core in time)

the old core was much more acceptant of community developer errors, the new core is strict, this means that it will fail if you do not respect the types, so if u use a string instead of an object, an array instead of an object it will fail in all apps that use stremio-core (as it is written in rust, so it's type safe)

**Comment by odd-willingness** [comment]
> the old core was much more acceptant of community developer errors, the new core is strict

This was it. Fixed a missing field that was probably acceptable with the old core. Working on all platforms now.

To elaborate, the issue was with meta pages on android mobile, android tv and web.

Thanks for the quick feedback.

**Comment by imcurs** [comment]
> > the old core was much more acceptant of community developer errors, the new core is strict
> 
> This was it. Fixed a missing field that was probably acceptable with the old core. Working on all platforms now.
> 
> To elaborate, the issue was with meta pages on android mobile, android tv and web.
> 
> Thanks for the quick feedback.

Could you tell me how you modified it? I have the same problem.

**Comment by aliyss** [comment]
@imcurs What fixed it for me was setting the same id that the item has when you provide for the catalog view as when you do for the meta view.

@jaruba For some reason the check does not exist when on desktop/web but only for android mobile (don't know about tv). Haven't had any complaints there.

In my opinion it was a great benefit not having to have the same id as now:

1. it just "glitches" over because I still can pass the imdbid. But the id doesn't match up.

https://github.com/user-attachments/assets/49d3cbdc-0acd-429c-af3c-c3dc776b0e1f

2. I can pass over control to another addon providing the metas. Catalog Meta id = syncribullet-5261617 -> after click -> Meta id kitsu-6273
