### ISSUE TITLE
Samsung TV with ccwgtv4k HDR10+ playback issue.

### ISSUE THREAD

**Issue by RayzRacer** [Stremio/stremio-bugs#977]
**Describe the bug**
The Problem - Samsung TVs Don't have Dolby Vision. Any File with DV/ HDR10+ Tag detects DV and switches to HDR10 ignoring the HDR10+. But When Playing a file with ONLY HDR10+ Tag it plays with HDR10+ without any problem. So Is there a way to play DV/HDR10+ tagged files with HDR10+ ? Many Samsung TV owners are facing this issue.
I'm on Google Chromecast 4K with Google TV.

**To Reproduce**
1. Play any File with tag DV/HDR10+
2. The File is played with only HDR tag
3. Now Play a File with Tag HDR10+ (No DV)
4. The File is played with HDR10+ 

**Expected behavior**
The Exoplayer should Identify if the TV can do DV or not. If it's not possible to do DV then check for HDR10+ format and if available play it with HDR10+ format. Don't jump into HDR without checking for HDR10+.

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**TV (please complete the following information):**
 - Device: Samsung QN90B TV with Chromecast with Google TV 4K.
 - OS: Google TV
 - Version Android 12

**Additional context**

**Comment by RayzRacer** [comment]
Yes. Same file when downloaded and played will play with HDR10+ format. Even with Stremio, when the file is played with external player like Kodi it is played with HDR10+. Only when played through Exoplayer the file does not play with HDR10+ and reverts to HDR.
That's why Expecting a solution so that Exoplayer can also play HDR10+ when given hybrid files with tags DV/HDR10+.

**Comment by TRtomasz** [comment]
Sorry, is this about Samsung app or android tv app?

**Comment by RayzRacer** [comment]
This is in Android TV app. 
My device - Chromecast with Google TV 4K connected to a Samsung TV.

**Comment by TRtomasz** [comment]
eveyrthing is fine i tried strema that is DV and HDR+ and it had HDR+ streams that are just DV + HDR are playing in hdr

**Comment by RayzRacer** [comment]
But it's not working for us Samsung TV owners. Not just me but many people are facing this issue.

**Comment by TRtomasz** [comment]
i'v tested it on samsung tv

**Comment by RayzRacer** [comment]
Can you confirm this once - You are on Samsung TV but 
1. The Stremio app is running on Chromecast with Google TV connected to the TV?
2. You are using Exoplayer for playback?

**Comment by TRtomasz** [comment]
No i have used firecube gen 3
i tried chromecast 4k now and it does not worh with hdr10+, but this is not app issue but device issue,
In the device settings when you go to HDR you will see it shows that HDR10+ is not supported  Settings > Display and Sound > Advanced display settings > Format selection > Show formats >

**Comment by RayzRacer** [comment]
But My Chromecast can Play HDR10+. 
It is also enabled in the Show Formats section. Attaching the image.
The proof for this is When I play a File with only HDR10+ (No DV) Tag in stremio it does play HDR10+. Try watching a episode of Silo (TV series) with HDR10+ file. It'll work.
![PXL_20241029_101043072](https://github.com/user-attachments/assets/c16446f5-0b8b-4a08-86c4-4279fc7a5335)

**Comment by TRtomasz** [comment]
After reseting chromecast it showed HDR10+ available for me too, but i tried playing same video in Just Player and VLC and it was the same result so my guess it is device specific issue since same video with different device plays correctly with HDR10+.

**Comment by RayzRacer** [comment]
Okay. All hope's lost then. Maybe it's a problem from Chromecast side which cannot handle a TV without Dolby Vision. So when it encounters DV/HDR10+ tag it reverts to HDR10. 
Thank you for your patience.

**Comment by briankinane** [comment]
I have the exact same issue. If you play a HDR10+ file in Stremio using the integrated ExoPlayer, it plays in HDR (but not HDR10+). If you click open in external player for the exact same file it can be played in HDR10+ in Kodi (You just have to disable Dolby Vision under Dynamic metadata formats in Kodi video settings).

This way, Kodi only attempts HDR10+ for dynamic metadata, then falls back to HDR.

Bearing this in mind, it looks like this issue only happens when Dolby Vision is attempted first as the Dynamic metadata format. The Google TV device does not attempt a second dynamic metadata format, it just defaults back to HDR.

This is an issue on both the GCCGTV and the new Google TV Streamer. (Which I bought especially for HDR10+ because my Nvidia Shield doesn't support HDR10+ and my Samsung TV doesn't support DV).

If there was any way the Stremio Devs could implement a feature similar to Kodis player settings where we could select which dynamic metadata format we want to use I think it would be amazing and would help so many users with Google devices and Samsung TVs.

Really appreciate all the work ye guys do. Hope you enjoy the holidays.

**Comment by briankinane** [comment]
https://github.com/xbmc/xbmc/pull/24584

The link above describes how they were able to implement the solution to allow the user to choose their desired HDR format.
