### ISSUE TITLE
[BUG] Metadata incomplete in discover on Stremio Windows

### ISSUE THREAD

**Issue by oleglucic** [Stremio/stremio-bugs#993]
It's not because data you see after opening the details is different tha one provided befor you open the details and both are controlled by imdb

_Originally posted by @TRtomasz in https://github.com/Stremio/stremio-bugs/issues/983#issuecomment-2447042749_

As you can see in the issue, it is not the addon's fault or the TMDB's fault. It is just stremio that doesn't fetch data correctly. Please reconsider this. Also, TMDB addons uses TMDB API and has nothing to do with IMDb

**Comment by TRtomasz** [comment]
Please do not spam repository with new issues as i said this is what tmdb addon returns and has nothing to do with the app
https://94c8cb9f702d-tmdb-addon.baby-beamup.club/catalog/movie/tmdb.top.json
this addons returns no additional info in the meta preview information thats why we show only genres because it is all it returns

**Comment by oleglucic** [comment]
Thank you 😊

**Comment by mrcanelas** [comment]
Hello @TRtomasz  the stremio client bug that I mentioned to @oleglucic  only happens with the android client, android TV and desktop this does not occur, it is the lack of information for movies in the android client, with series this which I believe to be a bug does not occur, only with movies, here are photos.

![Screenshot_20241104_171645_Stremio](https://github.com/user-attachments/assets/fec7d20d-5ae7-4fb1-9712-b28055d19a7f)
![Captura de Tela (24)](https://github.com/user-attachments/assets/48a24873-dc81-4469-8730-e7e02a86a62c)
